### PR TITLE
Defer drawing of title until colors are applied

### PR DESCRIPTION
**Pull request by davidsteinberger**
* ## A description of the changes proposed in the pull request:

This PR defers the drawing of the title until css variables are applied.
That prevents the *title-text* and the *title-value* to be drawn with the default styles as highlighted in #48.

* ## A reference to a related issue (if applicable):

#48

* ## @mentions of the person or team responsible for reviewing proposed changes:

@nonmetalhail @randyaskin 

* ## working tests:
#### The tests need to be functional and/or unit tests, written for the wct framework, and placed in the test folder, following our testing guidelines.

test added in 4c2a6e1

### CODE REVIEW

**Comment by benoitjchevalier** [comment]
Hello and thank you for you PR. This makes sense to us, however we already have a mechanism in place for listening to css var updates. 

Can you try listening to the `_stylesUpdated` property in the `_drawTitle` observer? Hopefully it should fix this issue as well as update the title colors when someone dynamically changes theme and call `updateStyles` on the chart

**Comment by davidsteinberger** [comment]
It's funny, b/c the approach is almost a copy found somewhere in px-vis. I'll update nevertheless.

I doubt, however, that it'll do what you describe. If I read the code correctly the *_titleGroup* is only drawn once, *fill, font-size* are not updated on redraw. Can I reapply these in the else block?

**Comment by benoitjchevalier** [comment]
Yeah the whole theming and color thing is pretty confusing. There are three different things:
 - `stylesUpdated`: called once at beginning and every time someone manually tries to update the colors. Should be used for css vars not related to series colors
- `seriesColorList` this will be updated with the new series colors pulled from the css vars. This will be read after a debounce and will typically be later than `stylesUpdated`. We use it internally, in general for updating the `completeSeriesConfig`. It won't necessary be updated if no theme is present
- `px-data-vis-colors-applied` has a similar "timing" as `seriesColorList`, this event is fired right after it. Guaranteed to be fired at least once, it generally is aimed for external components to catch (typically in our demos, but I wouldn't be surprised if it were used in vis internally as well)

Here I _think_ `stylesUpdated` makes more sense, but it might be that it still fires too early in this scenario... If it doesn't solve the issue then keep your current change and add a default to `_colorsAreSet` so that the title will still draw even with no theme in Polymer 1 and make `_colorsSet ` switch its value on/off (i.e `!_colorsAreSet`) so that further dynamic theme changes pick up the color change.

Hope this makes sense, the whole thing is pretty convoluted...

Just read the code, yes please update the `else` block, it should definitely try to pick up updated vars! I guess pie-chart hasn't been given some love in a while. Thanks for your time

**Comment by davidsteinberger** [comment]
Ben, I switched to *_stylesUpdated*. Note that I could only make it work with a `raf` in ready. As this is done in other places too, I hope that's ok. What do you think?

**Comment by benoitjchevalier** [comment]
Sounds good to me . Thanks for the PR David 👍 💯

**Comment by benoitjchevalier** [comment]
removed now unused listener and released it as `2.2.3`

**Pull request merged**
