### PR TITLE
basic structure for empty pie chart

### PR DESCRIPTION
**Pull request by xiaofanwu**

### CODE REVIEW

**Comment by mdwragg** [comment]
Hi,

Thanks for the pull request - please adhere to the PR template when submitting pull requests.

Also, please remove any commented out code/dead code and all `debugger` statements also.

I'm going to close this PR so you can open a new one explaining in greater detail the reason for the PR.

Thanks.

**Comment by benoitjchevalier** [comment]
I have something to handle empty pie chart data, I'll take the opportunity to deal with update and removal of data since I'm in there and update the repo soon.

**Comment by xiaofanwu** [comment]
Sounds good!  The PR is only for reference in case it is needed.  I left
the debuggers in areas where I made the changes,  so that it is easy to
see.  No need to merge,  just for reference.

Thanks and have a great weekend!

Xiaofan

**Comment by benoitjchevalier** [comment]
@xiaofanwu Pie should now support empty data as well as update to data in the latest version. Let me know if that works for you.

**Pull request closed without merging**
